import {
  Rss,
  Bookmark,
  Cloud,
  Calendar,
  Clock,
  Search,
  Activity,
  TrendingUp,
  Play,
  Tv,
  GitBranch,
  Globe,
  Flame,
  Code2,
  Package,
  Radio,
  Gamepad2,
  ListTodo,
  Server,
  Container,
  Layers,
  Columns,
  Wifi,
  Eye,
  Puzzle,
  type LucideComponent,
} from '@lucide/vue'

const iconMap: Record<string, LucideComponent> = {
  rss: Rss,
  bookmarks: Bookmark,
  html: Code2,
  weather: Cloud,
  clock: Clock,
  monitor: Activity,
  search: Search,
  videos: Play,
  'hacker-news': Flame,
  lobsters: Globe,
  reddit: Radio,
  markets: TrendingUp,
  'to-do': ListTodo,
  calendar: Calendar,
  'calendar-legacy': Calendar,
  releases: Package,
  repository: GitBranch,
  'server-stats': Server,
  'docker-containers': Container,
  'dns-stats': Wifi,
  'change-detection': Eye,
  'twitch-channels': Tv,
  'twitch-top-games': Gamepad2,
  iframe: Globe,
  extension: Puzzle,
  'custom-api': Code2,
  group: Layers,
  'split-column': Columns,
}

export function getWidgetIcon(type: string): LucideComponent {
  return iconMap[type] ?? Globe
}
